QUERY PASIVOS
Select RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_PROCESO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_RIF_CEDULA,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_BANCA,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SEGMENTO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBSEGMENTO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NOMBRE_CLIENTE,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NIVEL_SOCIOECON,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_GRUPO_ECONOMICO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NATURALEZA_PRODUCTO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO,
       RENTA.REN_PRODUCTO.PRD_NOMBRE_PRODUCTO,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO_ALTAIR,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBPRODUCTO_ALTAIR,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CUENTA_CONTABLE1,
       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_ESTATUS,
       Max(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_ULT_TRAN_D) As FECHA_ULT_TRANS,
       Count(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CONTRATO) As NUMERO_CONTRATOS,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SALDO) As SALDO,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PROMEDIO) As PROMEDIO,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NUMERO_DEBITOS) As NUM_DEBITOS,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_MONTO_DEBITOS) As MONTO_DEBITOS,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NUMERO_CREDITOS) As NUM_CREDITOS,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_MONTO_CREDITOS) As MONTO_CREDITOS,
       Sum(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_INTERESES) As INTERESES
 From RENTA.REN_MARGEN_CLIENTE_MENSUAL
 Inner Join RENTA.REN_PRODUCTO
    On RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO =
       RENTA.REN_PRODUCTO.PRD_CODIGO_PRODUCTO
 Where RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_PROCESO in ('31102022','30112022','31122022','31012023','28022023','31032023')
   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_RIF_CEDULA = 'J50019975'
   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NATURALEZA_PRODUCTO in (2,6)
   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO Not In (196,197,198,808,809)
   And SUBSTR(RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CUENTA_CONTABLE1,1,3) Not In ('231','241','611','819')
   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_BANCA Not In (5, 4)
   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_ESTATUS = 'A'
 Group By RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_PROCESO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_RIF_CEDULA,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_BANCA,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SEGMENTO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBSEGMENTO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NOMBRE_CLIENTE,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NIVEL_SOCIOECON,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_GRUPO_ECONOMICO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NATURALEZA_PRODUCTO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO,
          RENTA.REN_PRODUCTO.PRD_NOMBRE_PRODUCTO,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO_ALTAIR,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBPRODUCTO_ALTAIR,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CUENTA_CONTABLE1,
          RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_ESTATUS;