-- QUERY PROVEEDORES  CONSOLIDADO 

SELECT RENTA.REN_SNBENEFICIARIO.SNB_RIF_EMPRESA,
       RENTA.REN_CLIENTE.CLI_NOM_CLIENTE,
       COUNT( DISTINCT RENTA.REN_SNBENEFICIARIO.SNB_CI_BENEFIC),
       SUM(RENTA.REN_SNBENEFICIARIO.SNB_MTO_PCORRECTO)
  FROM RENTA.REN_SNBENEFICIARIO 
  LEFT JOIN RENTA.REN_SNORDENANTE 
    ON RENTA.REN_SNBENEFICIARIO.SNB_RIF_EMPRESA = RENTA.REN_SNORDENANTE.SNO_RIF_EMPRESA
   AND RENTA.REN_SNBENEFICIARIO.SNB_ID_DEBITO = RENTA.REN_SNORDENANTE.SNO_ID_DEBITO
  LEFT JOIN RENTA.REN_CLIENTE ON RENTA.REN_SNORDENANTE.SNO_RIF_EMPRESA = RENTA.REN_CLIENTE.CLI_RIF
 WHERE RENTA.REN_SNBENEFICIARIO.SNB_FEC_VALOR BETWEEN ('01012023') AND ('31012023')
   and RENTA.REN_SNORDENANTE.SNO_TIPO_PAGO = 'PROVEEDORE'
 GROUP BY RENTA.REN_SNBENEFICIARIO.SNB_RIF_EMPRESA,
          RENTA.REN_CLIENTE.CLI_NOM_CLIENTE

