Select RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_PROCESO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_RIF_CEDULA,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_BANCA,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SEGMENTO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBSEGMENTO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NOMBRE_CLIENTE,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NIVEL_SOCIOECON,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_GRUPO_ECONOMICO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NATURALEZA_PRODUCTO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CONTRATO,

       RENTA.REN_PRODUCTO.PRD_NOMBRE_PRODUCTO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO_ALTAIR,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SUBPRODUCTO_ALTAIR,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_CUENTA_CONTABLE1,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_ESTATUS,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_ULT_TRAN_D,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_APERTURA_D,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_MONTO_APERTURA, 

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_SALDO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PROMEDIO,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NUMERO_DEBITOS,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_MONTO_DEBITOS,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NUMERO_CREDITOS,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_MONTO_CREDITOS,

       RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_INTERESES

From RENTA.REN_MARGEN_CLIENTE_MENSUAL

 Inner Join RENTA.REN_PRODUCTO

    On RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_PRODUCTO =

       RENTA.REN_PRODUCTO.PRD_CODIGO_PRODUCTO

 Where RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_FECHA_PROCESO = '31012023'

   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_NATURALEZA_PRODUCTO = 1

   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_BANCA Not In (5, 14)

   And RENTA.REN_MARGEN_CLIENTE_MENSUAL.MCL_ESTATUS = 'A'